# Generated by Django 4.2 on 2024-03-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=13, verbose_name="Phone Number"),
        ),
    ]
