# Generated by Django 4.2 on 2024-03-02 16:27

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(max_length=50, verbose_name="address 1"),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(max_length=50, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=django_countries.fields.CountryField(
                default="Egypt", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="wa_phone",
            field=models.CharField(max_length=14, verbose_name="Whatsapp Phone Number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=14, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="wa_phone",
            field=models.CharField(max_length=14, verbose_name="Whatsapp Phone Number"),
        ),
    ]
