# Generated by Django 4.2 on 2024-03-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(max_length=13, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="company",
            name="wa_phone",
            field=models.CharField(max_length=13, verbose_name="Whatsapp Phone Number"),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(max_length=13, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="person",
            name="wa_phone",
            field=models.CharField(max_length=13, verbose_name="Whatsapp Phone Number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="wa_phone",
            field=models.CharField(max_length=13, verbose_name="Whatsapp Phone Number"),
        ),
    ]
