# Generated by Django 4.2 on 2024-03-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_wa_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="wa_phone",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="Whatsapp Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=11, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="wa_phone",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="Whatsapp Phone Number"
            ),
        ),
    ]
