# Generated by Django 4.2 on 2024-03-21 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_alter_company_phone_number_alter_company_wa_phone_and_more"),
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yarn",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.CreateModel(
            name="YarnInventory",
            fields=[
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total weight"
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cartoon", "Cartoon"),
                            ("Bag", "Bag"),
                            ("Box", "Box"),
                            ("Pieces", "Pieces"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="unit type",
                    ),
                ),
                (
                    "quantity_per_unit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="quantity per type"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total price"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actual_existing_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="actual existing weight",
                    ),
                ),
                ("recieved_at", models.DateTimeField(verbose_name="received at")),
                (
                    "located_at",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="located at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Buyed", "Buyed"),
                            ("Sold Out", "Sold Out"),
                            ("Returned", "Returned"),
                            ("Out of Stock", "Out of Stock"),
                            ("New Raw", "New Raw"),
                            ("In Dyeing", "In Dyeing"),
                            ("In Production", "In Production"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="discount",
                    ),
                ),
                (
                    "added_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="added tax",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.person",
                        verbose_name="supplier",
                    ),
                ),
                (
                    "yarn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.yarn",
                        verbose_name="yarn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yarn In Inventory",
                "verbose_name_plural": "Yarns In Inventory",
            },
        ),
        migrations.CreateModel(
            name="SoldYarn",
            fields=[
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total weight"
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cartoon", "Cartoon"),
                            ("Bag", "Bag"),
                            ("Box", "Box"),
                            ("Pieces", "Pieces"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="unit type",
                    ),
                ),
                (
                    "quantity_per_unit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="quantity per type"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total price"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sold_at", models.DateTimeField(verbose_name="Sold At")),
                (
                    "added_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="added tax",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="discount",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.person",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Seller",
                    ),
                ),
                (
                    "yarn_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.yarninventory",
                        verbose_name="Yarn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sold Yarn",
                "verbose_name_plural": "Sold Yarns",
                "ordering": ["yarn_inventory", "customer", "sold_at"],
            },
        ),
    ]
