# Generated by Django 4.2 on 2024-04-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yarninventory",
            name="recieved_at",
            field=models.DateField(verbose_name="received at"),
        ),
    ]
