# Generated by Django 4.2 on 2024-04-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_alter_yarninventory_recieved_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabricdyeingfactory",
            name="came_out_at",
            field=models.DateField(verbose_name="Came Out At"),
        ),
        migrations.AlterField(
            model_name="fabricdyeinginventory",
            name="recieved_at",
            field=models.DateField(blank=True, null=True, verbose_name="received At"),
        ),
        migrations.AlterField(
            model_name="fabricinventory",
            name="recieved_at",
            field=models.DateField(blank=True, null=True, verbose_name="received At"),
        ),
        migrations.AlterField(
            model_name="returnedfabric",
            name="returned_at",
            field=models.DateField(verbose_name="Returned At"),
        ),
        migrations.AlterField(
            model_name="returnedyarn",
            name="returned_at",
            field=models.DateField(verbose_name="Returned At"),
        ),
        migrations.AlterField(
            model_name="soldfabric",
            name="sold_at",
            field=models.DateField(verbose_name="Sold At"),
        ),
        migrations.AlterField(
            model_name="soldyarn",
            name="sold_at",
            field=models.DateField(verbose_name="Sold At"),
        ),
        migrations.AlterField(
            model_name="yarnfactory",
            name="orderd_at",
            field=models.DateField(verbose_name="Orderd At"),
        ),
    ]
