# Generated by Django 4.2 on 2024-03-22 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0003_fabricdyeinginventory_fabricinventory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fabricdyeinginventory",
            old_name="actual_existing_weight",
            new_name="existing_weight",
        ),
        migrations.RenameField(
            model_name="fabricinventory",
            old_name="actual_existing_weight",
            new_name="existing_weight",
        ),
        migrations.RenameField(
            model_name="yarninventory",
            old_name="actual_existing_weight",
            new_name="existing_weight",
        ),
    ]
