# Generated by Django 4.2 on 2024-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0004_alter_fabricinventory_recieved_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabricdyeinginventory",
            name="recieved_at",
            field=models.DateField(default="2024-04-29", verbose_name="received At"),
            preserve_default=False,
        ),
    ]
