# Generated by Django 4.2 on 2024-05-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0005_alter_fabricdyeinginventory_recieved_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabricdyeinginventory",
            name="recieved_at",
            field=models.DateField(blank=True, null=True, verbose_name="received At"),
        ),
        migrations.AlterField(
            model_name="fabricinventory",
            name="fabric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business.fabric",
                verbose_name="Farbic",
            ),
        ),
        migrations.AlterField(
            model_name="fabricinventory",
            name="recieved_at",
            field=models.DateField(blank=True, null=True, verbose_name="received At"),
        ),
    ]
