# Generated by Django 4.2 on 2024-06-05 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0006_alter_fabricdyeinginventory_recieved_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="soldyarn",
            options={
                "ordering": ["yarn_inventory", "customer", "-sold_at"],
                "verbose_name": "Sold Yarn",
                "verbose_name_plural": "Sold Yarns",
            },
        ),
    ]
